---

- name: undeploy | get template vm
  vmware.vmware_rest.vcenter_vm_info:
    filter_names:
    - "{{ rhel_vm }}"
  register: vms_info

- name: undeploy | stop the VM
  vmware.vmware_rest.vcenter_vm_power:
    state: stop
    vm: "{{ item.vm }}"
  with_items: '{{ vms_info.value }}'

- name: undeploy | undeploy the VM
  vmware.vmware_rest.vcenter_vm:
    state: absent
    vm: "{{ item.vm }}"
  with_items: '{{ vms_info.value }}'
