---

- name: Install Software
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - firewalld
      - httpd
      - php 
      - php-common
  become: yes

- name: Start firewalld
  service: 
    name: firewalld
      enabled: yes
      state: started
  become: true
  ignore_errors: yes

- name: Open port TCP 80
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled

- name: Webpage template
  template:
    src: ../templates/webpage.html.j2
    dest: /var/www/html/index.html
    owner: apache
    mode: "0644"
  become: yes
    
- name: Restart httpd server 
  service: 
    name: httpd
    enabled: yes
    state: restarted
  become: yes
 