---
- name: Same as above but subscribe to a specific pool by ID.
  community.general.redhat_subscription:
    state: present
    username: rh-ee-cparada
    password: eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiIyYTA2NWM0MmU3MjA0YzI1YWI4MmNkYmVlYzEyODc0YiJ9.qipInv25g9TToZxMbtI9Js2qhfTX4pug-pbBEW6igSIKz-zRhagDmctRS0mRTjT2Oe2fIDgDwDMDDyaGd5mOTp2Bf7teKdna94AkXkhPHPSwEgHMiJT9of7l--wvg8pzxBaP5VdGl0lYoHtHtZDOyJuc6BJV8_yF0iBQ1f8NHImaPYbwmwqxkv44WWigqadecSdwXSuxZD_Nbpm3SQ9IoPujIHMEYckPhimVkLbAfnBmHaBYChD8ArNqHnoW0Jsd7u03hGeD1uyqf71QVh9zmKIZFsDwfQK-E65yU9-GStif6MkL35WuC8DVrfBLTzbu25nikMlWloPp-TCBYjT-ctbbVVQ00Fgx3AQmjkTaU0NdXMaM-3UVI3PwEV6Emr4BWqhMz38h0Pj41l2Rc2GbwtUdOJYIcbUC9h2NiWSGlb8p-7EvbA4yi8daF4ttEn4T5iYQD1HVWOu10GjykB0TnYAkzf73yAk3D7cs3O57uS-0mnxrPVbTzxZS_VA28zOe0_LZPwbKlTeKkcrzMM5JxjD5hydDQlCm23UMk7ZaoQSynPazGZ807jW7iCCt_yoxKLZaTorER9h6fAJctOzoeRodDxyyfu_FdGugvyx0ePZyJTsX5ocF-RQXak3T5MW1ZliRP1yjz1G_KVqAPPSbzTmVgiYCBSgjTje7eQMEQsE
    pool_ids: 8a85f99c7d76f2fd017d96c9d5ed06b1

- name: Install Software
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - firewalld
      - httpd
      - php 
      - php-common
  become: yes

- name: Start firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: yes
    state: started
  become: true

- name: Open port TCP 80
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  become: true

- name: Webpage template
  ansible.builtin.template:
    src: ../templates/webpage.html.j2
    dest: /var/www/html/index.html
    owner: apache
    mode: "0644"
  become: yes
    
- name: Restart httpd server 
  ansible.builtin.service: 
    name: httpd
    enabled: yes
    state: restarted
  become: yes
 