---

# all
ansible_vmware_validate_certs: no
ansible_connection: ssh
#ansible_connection: vmware_tools
ansible_vmware_guest_path: "DC1/vm/"
ansible_vmware_tools_user: admin
ansible_vmware_tools_password: admin
vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"

# rhel
vm_name: rhel1
vm_template: rhl7
vm_cluster: cluster1
vm_datastore: datastore2
vm_folder: vm
vm_cpu: 1
vm_ram: 4

vm_ip: 192.168.1.41
